#### 간단한 신경망을 예로 실제로 기울기를 구하는 코드 구현

In [1]:
import sys, os
sys.path.append('C:/myStudy/ZeroKaraTsukuru/deep-learning-from-scratch-master')
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [2]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)  # 정규분포로 초기화
    
    # 예측을 수행
    def predict(self, x):
        return np.dot(x, self.W)
    
    # 손실함수의 값을 구함
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [3]:
net = simpleNet()

print(net.W)

[[-0.56766814  0.0404356  -0.85615632]
 [-0.81761407 -0.5636922  -0.92035431]]


In [4]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))

[-1.07645355 -0.48306162 -1.34201267]
1


In [5]:
t = np.array([0, 0, 1])
print(net.loss(x, t))

1.5400537331230433


In [6]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.16774318  0.30363491 -0.47137809]
 [ 0.25161477  0.45545237 -0.70706714]]


In [7]:
# 위 코드를 람다 함수로 변형
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.16774318  0.30363491 -0.47137809]
 [ 0.25161477  0.45545237 -0.70706714]]
